image: marcopeg/gitpod-workspace-postgres:2.5.0

tasks:
  - name: Utility
    init: rm -rf ./.gitpod.lock && npm i && touch ./.gitpod.lock
    command: echo "Hello Fetchq :-)"
    openIn: bottom
    openMode: tab-before
  - name: Unit Tests
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    init: echo "Awaiting NPM install..." && while ! find ./.gitpod.lock 2> /dev/null 1> /dev/null; do sleep 5; done
    command: yarn tdd:e2e
    openIn: right
    openMode: tab-after

ports:
  - port: 8008
    onOpen: ignore
  - port: 5432
    onOpen: ignore

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.1:DO6k4GCpqhwZcKo+jY9xjQ==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==
    - mikestead.dotenv@1.0.1:SSXjr5hZcbqSF7nMIhTNnA==
    - wayou.vscode-todo-highlight@1.0.4:8IqxuxCVol2WnScJc5xVzg==
